/* ============================================================
   AUDITORÍAS DISTRIBUIDORA – ESTILO "POR TABLA" (T-SQL)
   Basado en el patrón del proyecto IntegradorBDI (triggers por tabla).
   ============================================================ */

---------------------------------------------------------------
-- PRODUCTO
---------------------------------------------------------------
IF OBJECT_ID('dbo.PRODUCTO','U') IS NOT NULL
BEGIN
    IF OBJECT_ID('dbo.AUDITORIA_PRODUCTO','U') IS NULL
    BEGIN
        CREATE TABLE dbo.AUDITORIA_PRODUCTO(
            ID_AUDITORIA_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
            ID_PRODUCTO   INT         NOT NULL,
            NOMBRE        NVARCHAR(200) NOT NULL,
            PRECIO        DECIMAL(18,2) NOT NULL,
            STOCK         INT         NOT NULL,
            ID_CATEGORIA  INT         NULL,
            ID_PROVEEDOR  INT         NULL,
            FECHA         DATETIME    NOT NULL,
            USUARIOBD     VARCHAR(128) NOT NULL,
            OPERACION     VARCHAR(10)  NOT NULL
            -- Opcional: FK a PRODUCTO si no vas a borrar físico
            -- ,CONSTRAINT FK_AUD_PROD_PRODUCTO FOREIGN KEY(ID_PRODUCTO) REFERENCES dbo.PRODUCTO(ID_PRODUCTO)
        );
    END;

    IF OBJECT_ID('dbo.TRG_AUDITORIA_UPDATE_PRODUCTO','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_UPDATE_PRODUCTO;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_UPDATE_PRODUCTO
    ON dbo.PRODUCTO
    AFTER UPDATE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_PRODUCTO
        (ID_PRODUCTO,NOMBRE,PRECIO,STOCK,ID_CATEGORIA,ID_PROVEEDOR,FECHA,USUARIOBD,OPERACION)
        SELECT d.ID_PRODUCTO,d.NOMBRE,d.PRECIO,d.STOCK,d.ID_CATEGORIA,d.ID_PROVEEDOR,GETDATE(),SYSTEM_USER,'UPDATE'
        FROM deleted d;
    END;
    GO

    IF OBJECT_ID('dbo.TRG_AUDITORIA_DELETE_PRODUCTO','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_DELETE_PRODUCTO;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_DELETE_PRODUCTO
    ON dbo.PRODUCTO
    AFTER DELETE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_PRODUCTO
        (ID_PRODUCTO,NOMBRE,PRECIO,STOCK,ID_CATEGORIA,ID_PROVEEDOR,FECHA,USUARIOBD,OPERACION)
        SELECT d.ID_PRODUCTO,d.NOMBRE,d.PRECIO,d.STOCK,d.ID_CATEGORIA,d.ID_PROVEEDOR,GETDATE(),SUSER_SNAME(),'DELETE'
        FROM deleted d;
    END;
    GO
END
GO

---------------------------------------------------------------
-- CLIENTE
---------------------------------------------------------------
IF OBJECT_ID('dbo.CLIENTE','U') IS NOT NULL
BEGIN
    IF OBJECT_ID('dbo.AUDITORIA_CLIENTE','U') IS NULL
    BEGIN
        CREATE TABLE dbo.AUDITORIA_CLIENTE(
            ID_AUDITORIA_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
            ID_CLIENTE   INT           NOT NULL,
            RAZON_SOCIAL NVARCHAR(200) NOT NULL,
            CUIT         VARCHAR(20)   NULL,
            TELEFONO     NVARCHAR(50)  NULL,
            DIRECCION    NVARCHAR(250) NULL,
            FECHA        DATETIME      NOT NULL,
            USUARIOBD    VARCHAR(128)  NOT NULL,
            OPERACION    VARCHAR(10)   NOT NULL
        );
    END;

    IF OBJECT_ID('dbo.TRG_AUDITORIA_UPDATE_CLIENTE','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_UPDATE_CLIENTE;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_UPDATE_CLIENTE
    ON dbo.CLIENTE
    AFTER UPDATE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_CLIENTE
        (ID_CLIENTE,RAZON_SOCIAL,CUIT,TELEFONO,DIRECCION,FECHA,USUARIOBD,OPERACION)
        SELECT d.ID_CLIENTE,d.RAZON_SOCIAL,d.CUIT,d.TELEFONO,d.DIRECCION,GETDATE(),SYSTEM_USER,'UPDATE'
        FROM deleted d;
    END;
    GO

    IF OBJECT_ID('dbo.TRG_AUDITORIA_DELETE_CLIENTE','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_DELETE_CLIENTE;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_DELETE_CLIENTE
    ON dbo.CLIENTE
    AFTER DELETE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_CLIENTE
        (ID_CLIENTE,RAZON_SOCIAL,CUIT,TELEFONO,DIRECCION,FECHA,USUARIOBD,OPERACION)
        SELECT d.ID_CLIENTE,d.RAZON_SOCIAL,d.CUIT,d.TELEFONO,d.DIRECCION,GETDATE(),SUSER_SNAME(),'DELETE'
        FROM deleted d;
    END;
    GO

    -- Bloqueo de DELETE en CLIENTE (puedes moverlo a otra tabla si preferís)
    IF OBJECT_ID('dbo.TRG_DELETE_BLOCK_CLIENTE','TR') IS NOT NULL DROP TRIGGER dbo.TRG_DELETE_BLOCK_CLIENTE;
    GO
    CREATE TRIGGER dbo.TRG_DELETE_BLOCK_CLIENTE
    ON dbo.CLIENTE
    INSTEAD OF DELETE AS
    BEGIN
        SET NOCOUNT ON;
        PRINT 'No se permite la eliminación de registros en CLIENTE. Use baja lógica o contacte al administrador.';
        -- Nota: Si querés forzar error en lugar de PRINT, usa RAISERROR con severidad 16 y ROLLBACK.
        -- RAISERROR('No se permite la eliminación...',16,1); ROLLBACK TRANSACTION; RETURN;
    END;
    GO
END
GO

---------------------------------------------------------------
-- PROVEEDOR
---------------------------------------------------------------
IF OBJECT_ID('dbo.PROVEEDOR','U') IS NOT NULL
BEGIN
    IF OBJECT_ID('dbo.AUDITORIA_PROVEEDOR','U') IS NULL
    BEGIN
        CREATE TABLE dbo.AUDITORIA_PROVEEDOR(
            ID_AUDITORIA_PROVEEDOR INT IDENTITY(1,1) PRIMARY KEY,
            ID_PROVEEDOR  INT           NOT NULL,
            RAZON_SOCIAL  NVARCHAR(200) NOT NULL,
            CUIT          VARCHAR(20)   NULL,
            TELEFONO      NVARCHAR(50)  NULL,
            DIRECCION     NVARCHAR(250) NULL,
            FECHA         DATETIME      NOT NULL,
            USUARIOBD     VARCHAR(128)  NOT NULL,
            OPERACION     VARCHAR(10)   NOT NULL
        );
    END;

    IF OBJECT_ID('dbo.TRG_AUDITORIA_UPDATE_PROVEEDOR','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_UPDATE_PROVEEDOR;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_UPDATE_PROVEEDOR
    ON dbo.PROVEEDOR
    AFTER UPDATE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_PROVEEDOR
        (ID_PROVEEDOR,RAZON_SOCIAL,CUIT,TELEFONO,DIRECCION,FECHA,USUARIOBD,OPERACION)
        SELECT d.ID_PROVEEDOR,d.RAZON_SOCIAL,d.CUIT,d.TELEFONO,d.DIRECCION,GETDATE(),SYSTEM_USER,'UPDATE'
        FROM deleted d;
    END;
    GO

    IF OBJECT_ID('dbo.TRG_AUDITORIA_DELETE_PROVEEDOR','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_DELETE_PROVEEDOR;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_DELETE_PROVEEDOR
    ON dbo.PROVEEDOR
    AFTER DELETE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_PROVEEDOR
        (ID_PROVEEDOR,RAZON_SOCIAL,CUIT,TELEFONO,DIRECCION,FECHA,USUARIOBD,OPERACION)
        SELECT d.ID_PROVEEDOR,d.RAZON_SOCIAL,d.CUIT,d.TELEFONO,d.DIRECCION,GETDATE(),SUSER_SNAME(),'DELETE'
        FROM deleted d;
    END;
    GO
END
GO

---------------------------------------------------------------
-- PEDIDO
---------------------------------------------------------------
IF OBJECT_ID('dbo.PEDIDO','U') IS NOT NULL
BEGIN
    IF OBJECT_ID('dbo.AUDITORIA_PEDIDO','U') IS NULL
    BEGIN
        CREATE TABLE dbo.AUDITORIA_PEDIDO(
            ID_AUDITORIA_PEDIDO INT IDENTITY(1,1) PRIMARY KEY,
            ID_PEDIDO   INT           NOT NULL,
            ID_CLIENTE  INT           NOT NULL,
            FECHA       DATETIME      NOT NULL,
            ESTADO      NVARCHAR(30)  NULL,
            ID_EMPLEADO INT           NULL,
            TOTAL       DECIMAL(18,2) NULL,
            FECHA_AUD   DATETIME      NOT NULL,
            USUARIOBD   VARCHAR(128)  NOT NULL,
            OPERACION   VARCHAR(10)   NOT NULL
        );
    END;

    IF OBJECT_ID('dbo.TRG_AUDITORIA_UPDATE_PEDIDO','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_UPDATE_PEDIDO;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_UPDATE_PEDIDO
    ON dbo.PEDIDO
    AFTER UPDATE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_PEDIDO
        (ID_PEDIDO,ID_CLIENTE,FECHA,ESTADO,ID_EMPLEADO,TOTAL,FECHA_AUD,USUARIOBD,OPERACION)
        SELECT d.ID_PEDIDO,d.ID_CLIENTE,d.FECHA,d.ESTADO,d.ID_EMPLEADO,d.TOTAL,GETDATE(),SYSTEM_USER,'UPDATE'
        FROM deleted d;
    END;
    GO

    IF OBJECT_ID('dbo.TRG_AUDITORIA_DELETE_PEDIDO','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_DELETE_PEDIDO;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_DELETE_PEDIDO
    ON dbo.PEDIDO
    AFTER DELETE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_PEDIDO
        (ID_PEDIDO,ID_CLIENTE,FECHA,ESTADO,ID_EMPLEADO,TOTAL,FECHA_AUD,USUARIOBD,OPERACION)
        SELECT d.ID_PEDIDO,d.ID_CLIENTE,d.FECHA,d.ESTADO,d.ID_EMPLEADO,d.TOTAL,GETDATE(),SUSER_SNAME(),'DELETE'
        FROM deleted d;
    END;
    GO
END
GO

---------------------------------------------------------------
-- DETALLEPEDIDO
---------------------------------------------------------------
IF OBJECT_ID('dbo.DETALLEPEDIDO','U') IS NOT NULL
BEGIN
    IF OBJECT_ID('dbo.AUDITORIA_DETALLEPEDIDO','U') IS NULL
    BEGIN
        CREATE TABLE dbo.AUDITORIA_DETALLEPEDIDO(
            ID_AUDITORIA_DETALLE INT IDENTITY(1,1) PRIMARY KEY,
            ID_PEDIDO     INT            NOT NULL,
            ID_PRODUCTO   INT            NOT NULL,
            CANTIDAD      INT            NOT NULL,
            PRECIO_UNIT   DECIMAL(18,2)  NOT NULL,
            DESCUENTO     DECIMAL(5,2)   NULL,
            FECHA         DATETIME       NOT NULL,
            USUARIOBD     VARCHAR(128)   NOT NULL,
            OPERACION     VARCHAR(10)    NOT NULL
        );
    END;

    IF OBJECT_ID('dbo.TRG_AUDITORIA_UPDATE_DETALLEPEDIDO','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_UPDATE_DETALLEPEDIDO;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_UPDATE_DETALLEPEDIDO
    ON dbo.DETALLEPEDIDO
    AFTER UPDATE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_DETALLEPEDIDO
        (ID_PEDIDO,ID_PRODUCTO,CANTIDAD,PRECIO_UNIT,DESCUENTO,FECHA,USUARIOBD,OPERACION)
        SELECT d.ID_PEDIDO,d.ID_PRODUCTO,d.CANTIDAD,d.PRECIO_UNIT,d.DESCUENTO,GETDATE(),SYSTEM_USER,'UPDATE'
        FROM deleted d;
    END;
    GO

    IF OBJECT_ID('dbo.TRG_AUDITORIA_DELETE_DETALLEPEDIDO','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_DELETE_DETALLEPEDIDO;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_DELETE_DETALLEPEDIDO
    ON dbo.DETALLEPEDIDO
    AFTER DELETE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_DETALLEPEDIDO
        (ID_PEDIDO,ID_PRODUCTO,CANTIDAD,PRECIO_UNIT,DESCUENTO,FECHA,USUARIOBD,OPERACION)
        SELECT d.ID_PEDIDO,d.ID_PRODUCTO,d.CANTIDAD,d.PRECIO_UNIT,d.DESCUENTO,GETDATE(),SUSER_SNAME(),'DELETE'
        FROM deleted d;
    END;
    GO
END
GO

---------------------------------------------------------------
-- FACTURA
---------------------------------------------------------------
IF OBJECT_ID('dbo.FACTURA','U') IS NOT NULL
BEGIN
    IF OBJECT_ID('dbo.AUDITORIA_FACTURA','U') IS NULL
    BEGIN
        CREATE TABLE dbo.AUDITORIA_FACTURA(
            ID_AUDITORIA_FACTURA INT IDENTITY(1,1) PRIMARY KEY,
            ID_FACTURA  INT            NOT NULL,
            ID_PEDIDO   INT            NOT NULL,
            FECHA       DATETIME       NOT NULL,
            IMPORTE     DECIMAL(18,2)  NOT NULL,
            TIPO        VARCHAR(5)     NULL,
            NUMERO      VARCHAR(20)    NULL,
            FECHA_AUD   DATETIME       NOT NULL,
            USUARIOBD   VARCHAR(128)   NOT NULL,
            OPERACION   VARCHAR(10)    NOT NULL
        );
    END;

    IF OBJECT_ID('dbo.TRG_AUDITORIA_UPDATE_FACTURA','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_UPDATE_FACTURA;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_UPDATE_FACTURA
    ON dbo.FACTURA
    AFTER UPDATE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_FACTURA
        (ID_FACTURA,ID_PEDIDO,FECHA,IMPORTE,TIPO,NUMERO,FECHA_AUD,USUARIOBD,OPERACION)
        SELECT d.ID_FACTURA,d.ID_PEDIDO,d.FECHA,d.IMPORTE,d.TIPO,d.NUMERO,GETDATE(),SYSTEM_USER,'UPDATE'
        FROM deleted d;
    END;
    GO

    IF OBJECT_ID('dbo.TRG_AUDITORIA_DELETE_FACTURA','TR') IS NOT NULL DROP TRIGGER dbo.TRG_AUDITORIA_DELETE_FACTURA;
    GO
    CREATE TRIGGER dbo.TRG_AUDITORIA_DELETE_FACTURA
    ON dbo.FACTURA
    AFTER DELETE AS
    BEGIN
        SET NOCOUNT ON;
        INSERT INTO dbo.AUDITORIA_FACTURA
        (ID_FACTURA,ID_PEDIDO,FECHA,IMPORTE,TIPO,NUMERO,FECHA_AUD,USUARIOBD,OPERACION)
        SELECT d.ID_FACTURA,d.ID_PEDIDO,d.FECHA,d.IMPORTE,d.TIPO,d.NUMERO,GETDATE(),SUSER_SNAME(),'DELETE'
        FROM deleted d;
    END;
    GO
END
GO
